version: '3.8'

services:
  service_api:
    build:
      context: .
      dockerfile: DiplomProject.Backend.Api/Dockerfile
    container_name: service_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5120:80"
    depends_on:
      - service_image
      - service_doc
    networks:
      - appnet

  service_image:
    build:
      context: .
      dockerfile: DiplomProject.Backend.ImageProcessingService/Dockerfile
    container_name: service_image
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - S3_Access_key=i7tLZg7cKz9SVRwTEKRVia
      - S3_Secret_key=a27QiqQq64j93yKnTbeaeHqWMcCmxJ3WrUTvgLMfy9KZ
    ports:
      - "5127:80"
    networks:
      - appnet

  service_doc:
    build:
      context: .
      dockerfile: DiplomProject.Backend.DocumentProcessingService/Dockerfile
    container_name: service_doc
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - S3_Access_key=i7tLZg7cKz9SVRwTEKRVia
      - S3_Secret_key=a27QiqQq64j93yKnTbeaeHqWMcCmxJ3WrUTvgLMfy9KZ
    ports:
      - "5109:80"
    networks:
      - appnet

  

networks:
  appnet:
    driver: bridge
