name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: https://${{secrets.SSH_HOST}}:5120
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name
        id: repo
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV  # lowercased

      - name: List build context files
        run: |
          echo "Listing files in ./DiplomProject.Backend.TextScanner:"
          ls -la ./DiplomProject.Backend.TextScanner

      - name: Build and Push Images
        run: |
          docker build -t ghcr.io/bober23/diplomproject-api:latest -f DiplomProject.Backend.Api/Dockerfile .
          docker build -t ghcr.io/bober23/diplomproject-scanner:latest -f DiplomProject.Backend.TextScanner/Dockerfile ./DiplomProject.Backend.TextScanner
          docker build -t ghcr.io/bober23/diplomproject-image:latest -f DiplomProject.Backend.ImageProcessingService/Dockerfile .
          docker build -t ghcr.io/bober23/diplomproject-doc:latest -f DiplomProject.Backend.DocumentProcessingService/Dockerfile .
          docker build -t ghcr.io/bober23/diplomproject-client:latest -f DiplomProject.Front/front/Dockerfile ./DiplomProject.Front/front

          docker push ghcr.io/bober23/diplomproject-api:latest
          docker push ghcr.io/bober23/diplomproject-image:latest
          docker push ghcr.io/bober23/diplomproject-doc:latest
          docker push ghcr.io/bober23/diplomproject-client:latest
          docker push ghcr.io/bober23/diplomproject-scanner:latest
  deploy:
    name: Deploy To Server
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload docker-compose to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/diplom/"

      - name: SSH into server and restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u bober23 --password-stdin
            docker compose -f /home/diplom/docker-compose.yml pull
            docker compose -f /home/diplom/docker-compose.yml down
            docker compose -f /home/diplom/docker-compose.yml up -d --pull always --no-build
